SELECT CEILING(12.3333323) -- TRAZ O MAIOR NUMERO INTEIRO PROXIMO AO QUE FOI PASSADO COMO PARAMETRO

SELECT FLOOR(12.3333323)  -- TRAZ O MENOR NUMERO INTEIRO PROXIMO AO QUE FOI PASSADO COMO PARAMETRO

SELECT RAND() -- TRAZ UM NUMERO ALEATORIO

SELECT ROUND(12.3333323, 2) -- arredonda para o tanto de casas desejadas apos a virgula

SELECT NUMERO, SUM(ROUND((QUANTIDADE*PREÇO),2)) AS FATURAMENTO FROM [ITENS NOTAS FISCAIS]
GROUP BY NUMERO

--Na tabela de notas fiscais, temos o valor do imposto.
--Já na tabela de itens, temos a quantidade e o faturamento.
--Calcule o valor do imposto pago no ano de 2016, arredondando
--para o menor inteiro.
SELECT FLOOR(SUM(([ITENS NOTAS FISCAIS].QUANTIDADE*[ITENS NOTAS FISCAIS].PREÇO)*IMPOSTO))
FROM [NOTAS FISCAIS] 
INNER JOIN [ITENS NOTAS FISCAIS] 
ON [NOTAS FISCAIS].NUMERO = [ITENS NOTAS FISCAIS].NUMERO
WHERE YEAR(DATA) = 2016

