SELECT CONVERT(VARCHAR, GETDATE(), 101)

SELECT CONVERT(VARCHAR, GETDATE(), 113)

SELECT CONVERT(VARCHAR, GETDATE(), 130)

SELECT CONVERT(DECIMAL(10,5), 193.57)

SELECT 'O PREÇO DO PRODUTO ' + [NOME DO PRODUTO] + ' É ' + CONVERT(VARCHAR, [PREÇO DE LISTA])
FROM [TABELA DE PRODUTOS]
