-- FUNÇÕES

SELECT LTRIM('     OLA') -- TIRA OS CARACTERES EM BRANCO DO LADO ESQUEDRO DA STRING

SELECT RTRIM('OLA     ') -- TIRA OS CARACTERES EM BRANCO DO LADO DIREITO DA STRING

SELECT CONCAT('OLA ', 'TUDO BEM') --  CONCATENA N STRING
SELECT CONCAT('OLA ', 'TUDO BEM ', '?') --  CONCATENA N STRING

SELECT ('OLA ' + 'TUDO BEM') -- DA PRA CONCATENAR USANDO O SINAL DE + 

SELECT LEFT ('RUA AUGUSTA',3) -- SELECIONA OS 3 CARACTERES DO LADO ESQUERDO DA STRING

SELECT RIGHT ('RUA AUGUSTA',7)-- SELECIONA OS 7 CARACTERES DO LADO DIREITO DA STRING

SELECT UPPER('rua augusta') -- DEIXA A SAIDA EM CAIXA ALTA

SELECT LOWER('RUA AUGUSTA') -- DEIXA A SAIDA EM CAIXA BAIXA

SELECT REPLACE ('R. AUGURSTA', 'R.','RUA') -- TROCA AONDE TIVER " R. " POR "RUA"

SELECT SUBSTRING ('RUA AUGUSTA',1,3) -- GERAR UMA SUBSTRING DO CARACTER 1 E PEGA OS 3 PROXIMOS CARACTERES

SELECT LEN ('RUA AUGUSTA') --  CONTA A QUANTIDADE DE CARACTERES

-- CONCATENANDO O NOME E O CPF DOS CLIETES
SELECT CONCAT( NOME, ' (', CPF, ') ') FROM [TABELA DE CLIENTES]

-- Faça uma consulta que lista o nome do cliente e o endereço completo
-- (com rua, bairro, cidade e estado).
SELECT NOME, CONCAT([ENDERECO 1] ,' ', BAIRRO ,' ', CIDADE ,' ', ESTADO ) FROM [TABELA DE CLIENTES]
