-- Gerando relatorio para saber o faturamento de cada sabor no ano de 2016

SELECT TP.SABOR FROM [TABELA DE PRODUTOS] TP

SELECT NF.DATA FROM [NOTAS FISCAIS] NF

SELECT (INF.QUANTIDADE*INF.PREÇO) AS FATURAMENTO FROM [ITENS NOTAS FISCAIS] INF

SELECT TP.SABOR, NF.DATA, (INF.QUANTIDADE*INF.PREÇO) AS FATURAMENTO
FROM [ITENS NOTAS FISCAIS] INF INNER JOIN [TABELA DE PRODUTOS] TP
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO

SELECT TP.SABOR, YEAR(NF.DATA) AS ANO, SUM(INF.QUANTIDADE*INF.PREÇO) AS FATURAMENTO
FROM [ITENS NOTAS FISCAIS] INF INNER JOIN [TABELA DE PRODUTOS] TP
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO
GROUP BY SABOR, YEAR(NF.DATA)


SELECT AUX1.SABOR, AUX1.ANO, AUX1.FATURAMENTO,
CONVERT(VARCHAR,ROUND((AUX1.FATURAMENTO/AUX2.TOTAL)*100,2)) + ' %' AS PERCENTUAL
FROM
(SELECT TP.SABOR, YEAR(NF.DATA) AS ANO, SUM(INF.QUANTIDADE*INF.PREÇO) AS FATURAMENTO
FROM [ITENS NOTAS FISCAIS] INF INNER JOIN [TABELA DE PRODUTOS] TP
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA) = 2016
GROUP BY SABOR, YEAR(NF.DATA)) AUX1
INNER JOIN
(SELECT YEAR(NF.DATA) AS ANO, SUM(INF.QUANTIDADE*INF.PREÇO) AS TOTAL
FROM [ITENS NOTAS FISCAIS] INF INNER JOIN [TABELA DE PRODUTOS] TP
ON TP.[CODIGO DO PRODUTO] = INF.[CODIGO DO PRODUTO]
INNER JOIN [NOTAS FISCAIS] NF
ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA) = 2016
GROUP BY YEAR(NF.DATA))AUX2
ON AUX1.ANO = AUX2.ANO
ORDER BY AUX1.FATURAMENTO DESC