-- Consultas com GROUP BY

SELECT ESTADO,[LIMITE DE CREDITO] FROM [TABELA DE CLIENTES]

-- FAZ A CONSULTA, AGRUPA POR ESTADO E FAZ A SOMA DE LIMITE DE CREDITO POR ESTADO
SELECT ESTADO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] GROUP BY ESTADO.

-- FAZ A CONSULTA, AGRUPA POR ESTADO E FAZ A MEDIA DE LIMITE DE CREDITO POR ESTADO
SELECT ESTADO, AVG([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] GROUP BY ESTADO

-- AGRUPA POR EMBALGEM E SELECIONA O MAIOR PRECO DE LISTA DE CADA EMBALGEM
SELECT EMBALAGEM, MAX([PREÇO DE LISTA]) FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM

-- AGRUPA POR EMBALGEM E SELECIONA O MENOR PRECO DE LISTA DE CADA EMBALGEM
SELECT EMBALAGEM, MIN([PREÇO DE LISTA]) FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM

-- AGRUPA POR EMBALGEM E SELECIONA O QUANTIDADE DE PRODUTOS DE CADA EMBALGEM
SELECT EMBALAGEM, COUNT([PREÇO DE LISTA]) FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM

-- SELECIONA O LIMITE DE CREDITO POR BAIRRO, SOMENTE PARA O ESTADO DE SP
SELECT BAIRRO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES]
WHERE ESTADO = 'SP'GROUP BY BAIRRO


--Aproveitando o exercício anterior, 
--quantos itens de venda existem com a 
--maior quantidade de venda para o produto '1101035'?
SELECT COUNT(*) FROM [ITENS NOTAS FISCAIS]
WHERE [CODIGO DO PRODUTO] = '1101035'
AND QUANTIDADE = 99