-- HAVING É USANDO DEPOIS DO GROUP BY PARA FILTRAR
SELECT BAIRRO, SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES]
WHERE ESTADO = 'SP' GROUP BY BAIRRO HAVING SUM([LIMITE DE CREDITO]) >= 140000

SELECT EMBALAGEM, SUM([PREÇO DE LISTA]), MAX([PREÇO DE LISTA]), MIN([PREÇO DE LISTA])
FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM

SELECT EMBALAGEM, SUM([PREÇO DE LISTA]), MAX([PREÇO DE LISTA]), MIN([PREÇO DE LISTA])
FROM [TABELA DE PRODUTOS] GROUP BY EMBALAGEM HAVING SUM([PREÇO DE LISTA]) <= 80

-- Quais são os clientes que fizeram mais de 2000 compras em 2016?
SELECT CPF, COUNT(*) FROM [NOTAS FISCAIS]
WHERE YEAR(DATA) = 2016 
GROUP BY CPF 
HAVING COUNT(*) > 2000
