--Ordenando saida de uma consulta
-- ORDENA A CONSULTA POR PREÇO DE LISTA
SELECT * FROM [TABELA DE PRODUTOS] ORDER BY [PREÇO DE LISTA]

-- ORDENA A CONSULTA POR PREÇO DE LISTA DE FOR DECRESCENTE
SELECT * FROM [TABELA DE PRODUTOS] ORDER BY [PREÇO DE LISTA] DESC

-- ORDENA A CONSULTA COM 2 CRITERIOS, PRIMEIRO ORDENANDO POR EMBALAGEM, DEPOIS ORDENA POR NOME DO PRODUTO
SELECT [EMBALAGEM], [NOME DO PRODUTO] FROM [TABELA DE PRODUTOS]
ORDER BY EMBALAGEM, [NOME DO PRODUTO]

--Qual foi a maior venda do produto
--"Linha Refrescante - 1 Litro - Morango/Limão", em quantidade?
--(Obtenha este resultado usando 2 SQLs).
SELECT * FROM [TABELA DE PRODUTOS] 
WHERE [NOME DO PRODUTO] = 'Linha Refrescante - 1 Litro - Morango/Limão'

SELECT * FROM [ITENS NOTAS FISCAIS]
WHERE [CODIGO DO PRODUTO] = '1101035'
ORDER BY QUANTIDADE DESC