DROP PROCEDURE [TratarErroZeroTry2]
CREATE PROCEDURE [dbo].[TratarErroZeroTry2] @CPF VARCHAR(12), @ANO INT, @DENOMINADOR INT,
@MENSAGEM VARCHAR(MAX) OUTPUT
AS
BEGIN
	BEGIN TRY
		SELECT SUM(A.QUANTIDADE * A.[PREÇO]) AS FATURAMENTO,
		(SUM(A.QUANTIDADE * A.[PREÇO])/@DENOMINADOR) AS COMISSAO
		FROM [ITENS NOTAS FISCAIS] A INNER JOIN [NOTAS FISCAIS] B
		ON A.NUMERO = B.NUMERO WHERE B.CPF = @CPF AND YEAR(B.DATA) = @ANO
	END TRY
	BEGIN CATCH
		SET @MENSAGEM = 'Houve um erro número: ' + CONVERT(VARCHAR(10),ERROR_NUMBER()) + ' - ' 
		SET @MENSAGEM = @MENSAGEM + 'Mensagem: ' + ERROR_MESSAGE() + ' - '
		SET @MENSAGEM = @MENSAGEM + 'Grau de severidade do erro: ' + CONVERT(VARCHAR(10),ERROR_SEVERITY()) + ' - '
		SET @MENSAGEM = @MENSAGEM + 'Estado do erro: ' + CONVERT(VARCHAR(10),ERROR_STATE()) + ' - '
		SET @MENSAGEM = @MENSAGEM + 'Numero da linha: ' + CONVERT(VARCHAR(10),ERROR_LINE()) + ' - '
		SET @MENSAGEM = @MENSAGEM + 'Procedure: ' + ERROR_PROCEDURE()
	END CATCH	
END

DECLARE @DENOMINADOR INT,
        @CPF VARCHAR (12),
		@ANO INT,
		@MENSAGEM VARCHAR(MAX);

SET @CPF = '1471156710'
SET @ANO = 2016
SET @DENOMINADOR = 0
SET @MENSAGEM = '';

EXEC TratarErroZeroTry2 @CPF = @CPF, @ANO = @ANO, @DENOMINADOR = @DENOMINADOR, @MENSAGEM = @MENSAGEM OUTPUT

IF @MENSAGEM <> ''
	PRINT @MENSAGEM
