-- USANDO A VARIAVEL @@ERROR E @@ROWCOUNT

CREATE PROCEDURE TratarErroZero @CPF VARCHAR(12), @ANO INT, @DENOMINADOR INT,
@NUMERRO INT OUTPUT, @NUMLINHA INT OUTPUT
AS
BEGIN
	SELECT SUM(A.QUANTIDADE * A.[PREÇO]) AS FATURAMENTO,
	(SUM(A.QUANTIDADE * A.[PREÇO])/@DENOMINADOR) AS COMISSAO
	FROM [ITENS NOTAS FISCAIS] A INNER JOIN [NOTAS FISCAIS] B
	ON A.NUMERO = B.NUMERO WHERE B.CPF = @CPF AND YEAR(B.DATA) = @ANO
	SELECT @NUMERRO = @@ERROR, @NUMLINHA = @@ROWCOUNT
END

DECLARE @DENOMINADOR INT,
        @CPF VARCHAR (12),
		@ANO INT,
		@NUMERRO INT,
		@NUMLINHA INT;

SET @CPF = 1471156710;
SET @ANO = 2016;
SET @DENOMINADOR = 0;

EXEC TratarErroZero @CPF = @CPF, @ANO = @ANO, @DENOMINADOR = @DENOMINADOR,
@NUMERRO = @NUMERRO OUTPUT, @NUMLINHA = @NUMLINHA OUTPUT

IF @NUMERRO <> 0
	PRINT 'HOUVE UM ERRO ' + CONVERT(VARCHAR(30),@NUMERRO) + ' - ' + CONVERT(VARCHAR(30),@NUMLINHA)