-- CRIANDO PROCEDURE
CREATE PROCEDURE BuscaEntidades @ENTIDADE AS VARCHAR(10)
AS
BEGIN
	IF @ENTIDADE = 'CLIENTES'
		SELECT CPF AS IDENTIFICADOR, NOME AS DESCRITOR, BAIRRO FROM [TABELA DE CLIENTES]
	ELSE IF @ENTIDADE = 'VENDEDORES'
		SELECT MATRICULA AS IDENTIFICADOR, NOME AS DESCRITOR, BAIRRO FROM [TABELA DE VENDEDORES]
END

EXEC BuscaEntidades @ENTIDADE = 'CLIENTES'
EXEC BuscaEntidades @ENTIDADE = 'VENDEDORES'

