CREATE PROCEDURE CalculaIdade
AS
BEGIN
	UPDATE [TABELA DE CLIENTES] SET IDADE = DATEDIFF(YEAR,[DATA DE NASCIMENTO], GETDATE()) -- vai atualizar o campo idade de acordo com a data do sistema
END

-- inserindo um cliente sem o campo idade
INSERT INTO [TABELA DE CLIENTES] (CPF, NOME, [ENDERECO 1], BAIRRO, CIDADE, ESTADO, CEP, [DATA DE NASCIMENTO], SEXO, [LIMITE DE CREDITO],
[VOLUME DE COMPRA], [PRIMEIRA COMPRA])
VALUES
('12345678910','JOAO MACHADO','RUA PROJETADA A', 'MADUREIRA', 'Rio de Janeiro','RJ','20000',
'20000306', 'M',120000,120000,120000)

exec CalculaIdade

select * from [TABELA DE CLIENTES] where cpf = '12345678910'

