--PROCEDURES COM PARAMETROS DE SAIDA
DROP PROCEDURE RetornaValores
CREATE PROCEDURE RetornaValores
@CPF AS VARCHAR(12),
@ANO AS INT,
@NUM_NOTAS INT OUTPUT,
@FATURAMENTO FLOAT OUTPUT
AS
BEGIN
	SELECT @NUM_NOTAS = COUNT(*) FROM [NOTAS FISCAIS] WHERE CPF = @CPF AND YEAR([DATA]) = @ANO

	SELECT @FATURAMENTO = SUM([QUANTIDADE]*PREÇO) FROM [ITENS NOTAS FISCAIS] A
	INNER JOIN [NOTAS FISCAIS] B
	ON A.NUMERO = B.NUMERO
	WHERE B.CPF = @CPF AND YEAR([DATA]) = @ANO
END

DECLARE 
	@NUMERO_NOTA INT,
	@ANO INT,
	@FATURAMENTO FLOAT,
	@CPF VARCHAR(12)

SET @ANO = 2016
SET @CPF = '19290992743'

	EXEC RetornaValores @CPF = @CPF, @ANO = @ANO, @NUM_NOTAS = @NUMERO_NOTA OUTPUT, @FATURAMENTO = @FATURAMENTO OUTPUT
	SELECT @NUMERO_NOTA,@FATURAMENTO

	SELECT * FROM [TABELA DE CLIENTES]
