-- FUNÇAO QUE RETORNA UMA TABELA
SELECT * FROM [TABELA DE CLIENTES]

SELECT * FROM [NOTAS FISCAIS] WHERE CPF = '1471156710'

CREATE FUNCTION ListaNotasCliente (@CPF AS VARCHAR(12)) RETURNS TABLE
AS
RETURN SELECT * FROM [NOTAS FISCAIS] WHERE CPF = @CPF

SELECT * FROM ListaNotasCliente('1471156710')

SELECT A.CPF, (SELECT COUNT(*) FROM ListaNotasCliente(CPF)) AS NUM_NOTA
FROM [TABELA DE CLIENTES] A
