-- criando uma função

CREATE FUNCTION FaturamentoNota (@numero AS INT) RETURNS FLOAT
AS
BEGIN
	DECLARE @FATURAMENTO FLOAT
	SELECT @FATURAMENTO = SUM(QUANTIDADE*PREÇO) FROM [ITENS NOTAS FISCAIS] WHERE NUMERO = @numero
	RETURN @FATURAMENTO
END

SELECT numero, [dbo].[FaturamentoNota](numero) FROM [NOTAS FISCAIS]


CREATE FUNCTION NumeroNotas (@data AS DATE) RETURNS INT
AS
BEGIN
	DECLARE @NUMNOTAS INT
	SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS] 
    WHERE DATA = @data
	RETURN @NUMNOTAS
END

SELECT [dbo].[NUMERONOTAS]('20170202')