
CREATE FUNCTION FuncTabelaNotas (@DATA_INICIO DATE, @DATA_FIM DATE) RETURNS TABLE
AS
RETURN SELECT DISTINCT DATA, [dbo].[NUMERONOTAS](DATA) AS NUMERO 
    FROM [NOTAS FISCAIS] WHERE DATA >= @DATA_INICIO
        AND DATA <= @DATA_FIM

SELECT * FROM FuncTabelaNotas ('20170101', '20170110')
