 -- INSERINDO DADOS NA TABELAS PRODUTOS
INSERT INTO [TABELA DE PRODUTOS]
( [CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PREÇO DE LISTA])
VALUES
( '1040107', 'Light - 350 ml - Melancia', 'Lata', '350 ml', 'Melancia', 4.56)

INSERT INTO [TABELA DE PRODUTOS]
( [CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PREÇO DE LISTA])
VALUES
( '1037797', 'Clean - 2 Litros - Laranja', 'Pet', '2 Litros', 'Laranja', 16.01)

INSERT INTO [TABELA DE PRODUTOS]
( [CODIGO DO PRODUTO], [NOME DO PRODUTO], [EMBALAGEM], [TAMANHO], [SABOR], [PREÇO DE LISTA])
VALUES
( '1000889', 'Sabor de Montanha - 700 ml - Uva', 'Garrafa', '700 ml', 'Uva', 6.31)


-- INSERINDO DADOS NA TABELA DE VENDEDORES
INSERT INTO [TABELA DE VENDEDORES] 
( [MATRICULA], [NOME], [PERCENTUAL COMISSÃO] )
VALUES
( '00233', 'José Geraldo da Fonseca', 0.1)

INSERT INTO [TABELA DE VENDEDORES]
( [MATRICULA], [NOME], [PERCENTUAL COMISSÃO] )
VALUES
( '00235', 'Márcio Almeida Silva', 0.08)

INSERT INTO [TABELA DE VENDEDORES]
( [MATRICULA], [NOME], [PERCENTUAL COMISSÃO] )
VALUES
( '00236', 'Cláudia Morais', 0.08)

