CREATE DATABASE SUCOS_VENDAS_1; -- COMANDO PARA CRIAR UM BANCO DE DADOS

DROP DATABASE SUCOS_VENDAS_1; -- COMANDO PARA DELETAR UM BANCO DE DADOS EXISTENTE

-- COMANDO PARA CRIAR UM BANCO DO DADOS COM ALGUNS PARAMETROS DEFINIDOS POR VC, COMO CAMINHO ONDE VAI SER SALVO, TAMANHO INICIAL,  TAMANHO MAXIMO E DE QUANTO EM QUATO VAI CRESCER
CREATE DATABASE SALES_VENDAS_02
ON ( NAME = SUCO_VENDAS_DAT,  
    FILENAME = 'C:\TEMP\DATA\SALES_VENDAS_02.mdf',  
    SIZE = 10,  
    MAXSIZE = 50,  
    FILEGROWTH = 5 )  
LOG ON  
( NAME = SUCOS_VENDAS_LOG,  
    FILENAME = 'C:\TEMP\DATA\SALES_VENDAS_02.ldf',  
    SIZE = 5MB,  
    MAXSIZE = 25MB,  
    FILEGROWTH = 5MB )