--seleciona os clientes que moram no mesmo bairro que os vendedores
SELECT [TABELA DE VENDEDORES].BAIRRO, [TABELA DE VENDEDORES].NOME,
[TABELA DE CLIENTES].BAIRRO, [TABELA DE CLIENTES].NOME
FROM [TABELA DE VENDEDORES] 
INNER JOIN [TABELA DE CLIENTES]
ON [TABELA DE VENDEDORES].BAIRRO = [TABELA DE CLIENTES].BAIRRO

--seleciona todos os vendedores e os clientes que moram no mesmo bairro
SELECT [TABELA DE VENDEDORES].BAIRRO, [TABELA DE VENDEDORES].NOME,
[TABELA DE CLIENTES].BAIRRO, [TABELA DE CLIENTES].NOME
FROM [TABELA DE VENDEDORES] 
LEFT JOIN [TABELA DE CLIENTES]
ON [TABELA DE VENDEDORES].BAIRRO = [TABELA DE CLIENTES].BAIRRO

--seleciona todos os clientes e os vendedores que moram no mesmo bairro
SELECT [TABELA DE VENDEDORES].BAIRRO, [TABELA DE VENDEDORES].NOME,
[TABELA DE CLIENTES].BAIRRO, [TABELA DE CLIENTES].NOME
FROM [TABELA DE VENDEDORES] 
RIGHT JOIN [TABELA DE CLIENTES]
ON [TABELA DE VENDEDORES].BAIRRO = [TABELA DE CLIENTES].BAIRRO

-- seleciona todos os vendedores e clientes
SELECT [TABELA DE VENDEDORES].BAIRRO, [TABELA DE VENDEDORES].NOME,
[TABELA DE CLIENTES].BAIRRO, [TABELA DE CLIENTES].NOME
FROM [TABELA DE VENDEDORES] 
FULL JOIN [TABELA DE CLIENTES]
ON [TABELA DE VENDEDORES].BAIRRO = [TABELA DE CLIENTES].BAIRRO

