-- SELECIONA TODOS OS CLIENTES E QUANTIDADE DE COMPRAS DE CADA
--NOTA QUE O RESULTADO DO "Fábio Carvalho" É 1, MAS NA VDD ELE NÃO FEZ NENHUMA COMPRA,
--SÓ APARECE UM POIS O COUNT PEGA O RESULTADA DA LINHA DELE QUE FOI UM E RETORNA NO SELECT
SELECT [TABELA DE CLIENTES].NOME, COUNT(*) FROM [TABELA DE CLIENTES]
LEFT JOIN [NOTAS FISCAIS]
ON [TABELA DE CLIENTES].CPF = [NOTAS FISCAIS].CPF
GROUP BY [TABELA DE CLIENTES].NOME