-- CONSULTAS INNER JOIN

-- SELECIONA O VENDENDOR DE CADA NOTA FISCAL
SELECT * FROM [NOTAS FISCAIS] INNER JOIN [TABELA DE VENDEDORES] ON [NOTAS FISCAIS].MATRICULA = [TABELA DE VENDEDORES].MATRICULA

-- SELECIONA O VENDEDOR E A QUANTIDADE DE VENDAS QUE ELE TEVE
SELECT [TABELA DE VENDEDORES].MATRICULA, [TABELA DE VENDEDORES].NOME, COUNT(*) AS [QUANTIDADE DE VENDAS]
FROM [NOTAS FISCAIS] 
INNER JOIN [TABELA DE VENDEDORES] ON [NOTAS FISCAIS].MATRICULA = [TABELA DE VENDEDORES].MATRICULA
GROUP BY [TABELA DE VENDEDORES].MATRICULA, [TABELA DE VENDEDORES].NOME

-- SELECIONA O VENDEDOR E A QUANTIDADE DE VENDAS POR ANO
SELECT [TABELA DE VENDEDORES].MATRICULA, [TABELA DE VENDEDORES].NOME, YEAR(DATA) AS ANO, COUNT(*) AS [QUANTIDADE DE VENDAS]
FROM [NOTAS FISCAIS] 
INNER JOIN [TABELA DE VENDEDORES] ON [NOTAS FISCAIS].MATRICULA = [TABELA DE VENDEDORES].MATRICULA
GROUP BY [TABELA DE VENDEDORES].MATRICULA, [TABELA DE VENDEDORES].NOME,YEAR(DATA)

-- SELECIONA O VENDEDOR E A QUANTIDADE DE VENDAS POR ANO E ORDENA POR ANO E EM SEGUIDA POR NOME
SELECT [TABELA DE VENDEDORES].MATRICULA, [TABELA DE VENDEDORES].NOME, YEAR(DATA) AS ANO, COUNT(*) AS [QUANTIDADE DE VENDAS]
FROM [NOTAS FISCAIS] 
INNER JOIN [TABELA DE VENDEDORES] ON [NOTAS FISCAIS].MATRICULA = [TABELA DE VENDEDORES].MATRICULA
GROUP BY [TABELA DE VENDEDORES].MATRICULA, [TABELA DE VENDEDORES].NOME,YEAR(DATA)
ORDER BY YEAR(DATA), [TABELA DE VENDEDORES].NOME


--Obtenha o faturamento anual da empresa.
--Leve em consideração que o valor financeiro
--das vendas consiste em multiplicar a quantidade pelo preço.
SELECT YEAR(DATA), SUM((QUANTIDADE*PREÇO)) AS FATURAMENTO FROM [NOTAS FISCAIS] NF
INNER JOIN [ITENS NOTAS FISCAIS] INF
ON NF.NUMERO = INF.NUMERO
GROUP BY YEAR(DATA)


