-- ALTERANDO DADOS DA TABELA QUE ESTAVAM ERRADOS
UPDATE [TABELA DE PRODUTOS] SET 
EMBALAGEM = 'Lata',
[PREÇO DE LISTA] = 2.46
WHERE [CODIGO DO PRODUTO] = '544931'

UPDATE [TABELA DE PRODUTOS] SET 
EMBALAGEM = 'Garrafa'
WHERE [CODIGO DO PRODUTO] = '1078680'

UPDATE [TABELA DE VENDEDORES] SET
[PERCENTUAL COMISSÃO] = 0.11
WHERE MATRICULA = '00238'

UPDATE [TABELA DE VENDEDORES] SET
[NOME] = 'José Geraldo da Fonseca Junior'
WHERE MATRICULA = '00233'