-- cursores - Definição de cursor
DECLARE @NOME VARCHAR(200)
DECLARE CURSOR1 CURSOR FOR SELECT TOP 4 NOME FROM [TABELA DE CLIENTES]
OPEN CURSOR1
FETCH NEXT FROM CURSOR1 INTO @NOME
WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT @NOME
	FETCH NEXT FROM CURSOR1 INTO @NOME
END

DECLARE @LIMITE_CREDITO FLOAT,
		@LIMITE_CREDITO_ACUM FLOAT = 0;
DECLARE CURSOR2 CURSOR FOR SELECT [LIMITE DE CREDITO] FROM [TABELA DE CLIENTES]

OPEN CURSOR2
FETCH NEXT FROM CURSOR2 INTO @LIMITE_CREDITO
WHILE @@FETCH_STATUS = 0
BEGIN
	SET @LIMITE_CREDITO_ACUM = @LIMITE_CREDITO_ACUM + @LIMITE_CREDITO
	FETCH NEXT FROM CURSOR2 INTO @LIMITE_CREDITO
END
CLOSE CURSOR2
DEALLOCATE CURSOR2
SELECT @LIMITE_CREDITO_ACUM

SELECT SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES]