-- FUNÇÃO PARA TRAZER UMA ENTIDADE ALEATORIA(CLIENTE, VENDEDOR OU PRODUTO)

CREATE FUNCTION EntidadeAleatoria (@TIPO VARCHAR(12)) RETURNS VARCHAR(20)
AS
BEGIN
	DECLARE @TABELA TABLE(CODIGO VARCHAR(20))
	DECLARE @ENTIDADE_ALEATORIO VARCHAR(12),
			@VAL_INICIAL INT,
			@VAL_FINAL INT,
			@ALEATORIO INT,
			@CONTADOR INT;

	IF @TIPO = 'CLIENTE'
		INSERT INTO @TABELA (CODIGO) SELECT CPF AS CODIGO FROM [TABELA DE CLIENTES]
	IF @TIPO = 'VENDEDOR'
		INSERT INTO @TABELA (CODIGO) SELECT MATRICULA FROM [TABELA DE VENDEDORES]
	IF @TIPO = 'PRODUTO'
		INSERT INTO @TABELA (CODIGO) SELECT [CODIGO DO PRODUTO] FROM [TABELA DE PRODUTOS]

	SET @CONTADOR = 1
	SET @VAL_INICIAL = 1
	SELECT @VAL_FINAL = COUNT(*) FROM @TABELA
	SET @ALEATORIO = [dbo].[NumeroAleatorio](@VAL_INICIAL, @VAL_FINAL)
	DECLARE CURSOR1 CURSOR FOR SELECT CODIGO FROM @TABELA
	OPEN CURSOR1
	FETCH NEXT FROM CURSOR1 INTO @ENTIDADE_ALEATORIO
	WHILE @CONTADOR < @ALEATORIO
	BEGIN
	   FETCH NEXT FROM CURSOR1 INTO @ENTIDADE_ALEATORIO
	   SET @CONTADOR = @CONTADOR + 1
	END
	CLOSE CURSOR1
	DEALLOCATE CURSOR1
	RETURN @ENTIDADE_ALEATORIO
END


-- CLIENTE ALEATORIO
DECLARE @CLIENTE_ALEATORIO VARCHAR(12)
DECLARE @VENDEDOR_ALEATORIO VARCHAR(12)
DECLARE @PRODUTO_ALEATORIO VARCHAR(12)
DECLARE @VAL_INICIAL INT
DECLARE @VAL_FINAL INT
DECLARE @ALEATORIO INT
DECLARE @CONTADOR INT

SET @CONTADOR = 1
SET @VAL_INICIAL = 1
SELECT @VAL_FINAL = COUNT(*) FROM [TABELA DE CLIENTES]
SET @ALEATORIO = [dbo].[NumeroAleatorio](@VAL_INICIAL, @VAL_FINAL)
DECLARE CURSOR1 CURSOR FOR SELECT CPF FROM [TABELA DE CLIENTES]
OPEN CURSOR1
FETCH NEXT FROM CURSOR1 INTO @CLIENTE_ALEATORIO
WHILE @CONTADOR < @ALEATORIO
BEGIN
   FETCH NEXT FROM CURSOR1 INTO @CLIENTE_ALEATORIO
   SET @CONTADOR = @CONTADOR + 1
END
CLOSE CURSOR1
DEALLOCATE CURSOR1
SELECT @CLIENTE_ALEATORIO

-- VENDEDOR ALEATORIO
SET @CONTADOR = 1
SET @VAL_INICIAL = 1
SELECT @VAL_FINAL = COUNT(*) FROM [TABELA DE VENDEDORES]
SET @ALEATORIO = [dbo].[NumeroAleatorio](@VAL_INICIAL, @VAL_FINAL)
DECLARE CURSOR1 CURSOR FOR SELECT MATRICULA FROM [TABELA DE VENDEDORES]
OPEN CURSOR1
FETCH NEXT FROM CURSOR1 INTO @VENDEDOR_ALEATORIO
WHILE @CONTADOR < @ALEATORIO
BEGIN
   FETCH NEXT FROM CURSOR1 INTO @VENDEDOR_ALEATORIO
   SET @CONTADOR = @CONTADOR + 1
END
CLOSE CURSOR1
DEALLOCATE CURSOR1
SELECT @VENDEDOR_ALEATORIO

-- PRODUTO ALEATORIO
SET @CONTADOR = 1
SET @VAL_INICIAL = 1
SELECT @VAL_FINAL = COUNT(*) FROM [TABELA DE PRODUTOS]
SET @ALEATORIO = [dbo].[NumeroAleatorio](@VAL_INICIAL, @VAL_FINAL)
DECLARE CURSOR1 CURSOR FOR SELECT [CODIGO DO PRODUTO] FROM [TABELA DE PRODUTOS]
OPEN CURSOR1
FETCH NEXT FROM CURSOR1 INTO @PRODUTO_ALEATORIO
WHILE @CONTADOR < @ALEATORIO
BEGIN
   FETCH NEXT FROM CURSOR1 INTO @PRODUTO_ALEATORIO
   SET @CONTADOR = @CONTADOR + 1
END
CLOSE CURSOR1
DEALLOCATE CURSOR1
SELECT @PRODUTO_ALEATORIO



