-- INSERIDO NOTA ALEATORIA NA TABELAS DE NOTAS FISCAIS

DECLARE @CLIENTE VARCHAR(20),
		@VENDEDOR VARCHAR(20),
		@PRODUTO VARCHAR(20),
		@DATA DATE,
		@NUMERO INT,
		@IMPOSTO FLOAT,
		@NUM_ITENS INT,
		@CONTADOR INT,
		@QUANTIDADE INT,
		@PRECO FLOAT,
		@AUXPRODUTO INT;
DECLARE	@LISTAPRODUTOS TABLE (PRODUTO VARCHAR(20))


SET @DATA = '20220531'
SET @CLIENTE = [dbo].[EntidadeAleatoria]('CLIENTE')
SET @VENDEDOR = [dbo].[EntidadeAleatoria]('VENDEDOR')
SELECT @NUMERO = MAX(NUMERO) + 1 FROM [NOTAS FISCAIS]
SET @IMPOSTO = 0.18
SET @CONTADOR = 1
SET @NUM_ITENS = [dbo].[NumeroAleatorio](2, 10)

INSERT INTO [NOTAS FISCAIS] (CPF, MATRICULA, DATA, NUMERO, IMPOSTO)
VALUES (@CLIENTE, @VENDEDOR, @DATA, @NUMERO, @IMPOSTO)

WHILE @CONTADOR <= @NUM_ITENS
BEGIN
    SET @PRODUTO = [dbo].[EntidadeAleatoria]('PRODUTO')
	SELECT @AUXPRODUTO = COUNT(*) FROM @LISTAPRODUTOS WHERE PRODUTO = @PRODUTO

	IF @AUXPRODUTO = 0
	BEGIN
		SET @QUANTIDADE = [dbo].[NumeroAleatorio](5, 100)
		SELECT @PRECO = [PREÇO DE LISTA] FROM [TABELA DE PRODUTOS] 
			WHERE [CODIGO DO PRODUTO] = @PRODUTO
		INSERT INTO [ITENS NOTAS FISCAIS] 
			(NUMERO, [CODIGO DO PRODUTO], QUANTIDADE, PREÇO)
		VALUES (@NUMERO, @PRODUTO, @QUANTIDADE, @PRECO)
		SET @CONTADOR = @CONTADOR + 1
	END
	INSERT INTO @LISTAPRODUTOS (PRODUTO) VALUES (@PRODUTO)
END